### ISSUE TITLE
(Example Advanced TCP) Client receives buffer length (42), which does not match the type

### ISSUE THREAD

**Issue by chenhanxue0831** [gd-com/utils#40]
Temporal solution => Code get_u32() before get_u16(), and simply code get_string() without argument.
Not sure whether it is the alternative.

![Pro_Receive_buffer_length](https://user-images.githubusercontent.com/31240078/226154488-951a785e-a101-4aca-a546-01107b103300.jpg)

**Comment by Tilican** [comment]
Hey @tylerchentrial 
It's possible to know the Godot version ? 
Thx :D

**Comment by chenhanxue0831** [comment]
Thank you for the feedback :), it is Godot Engine 4.0, I know there are some differences between 3 and 4. In addition, I have tried TCP basic-SSL, and got error 1 when connect_to_stream(). The client-side's x509.cert is the same as the node server's x509.cert(Not sure whether it is the right way to access TLS cert). I am new to the network coding field. Privately change the code   as the following picture
![Pro_Basic_TLS_error_2](https://user-images.githubusercontent.com/31240078/226559272-76cc814a-7339-456e-a8ad-ca39ff94cd65.jpg)
And, I get error 1 not sure why is it.
![Pro_Basic_TLS_error_1](https://user-images.githubusercontent.com/31240078/226557296-1f512cf8-e45b-4ea1-829c-d4c1163b88cb.jpg)
